apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: test-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-app
    spec:
      containers:
        - name: test-app
          image: joe1534/app-with-argocd:1371525e91bbd9994dfb3a349d9600a77b934fde
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/app?serverTimezone=Asia/Seoul"
            - name: SPRING_DATASOURCE_USERNAME
              value: "app"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "app12345"