name: k8s test app with Github actions & Docker CI & ArgoCD

on:
  workflow_dispatch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Make Properties file
        run: |
          mkdir ./src/main/resources
          cd ./src/main/resources
          touch ./application.properties
          echo "${{ secrets.PROPERTIES }}" > ./application.properties
        shell: bash

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Naming jar file
        run: mv ./target/*.jar ./target/app.jar

      - name: Check jar file
        run: ls ./target

      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./target/*.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64 # 다중 플랫폼 설정
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOKERHUB_REPOSITORY }}:${{ github.sha }}

    outputs:
      docker_repo: ${{ secrets.DOKERHUB_REPOSITORY }}
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      image_tag: ${{ github.sha }}

  argocd:
    runs-on: ubuntu-latest

    needs: ci

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.TOKEN }}

      - name: Set up Image
        run: |
          IMAGE_TAG="${{ needs.ci.outputs.docker_username }}/${{ needs.ci.outputs.docker_repo }}:${{ needs.ci.outputs.image_tag }}"
          
          # Debugging: Print out the variables
          echo "IMAGE_TAG=$IMAGE_TAG"
          echo "DOCKER_USERNAME=${{ needs.ci.outputs.docker_username }}"
          echo "DOCKER_REPO=${{ needs.ci.outputs.docker_repo }}"
          
          # Modify the deployment.yaml file with the new image tag
          sed -i "s%image: ${{ needs.ci.outputs.docker_username }}/${{ needs.ci.outputs.docker_repo }}:.*%image: $IMAGE_TAG%" manifest/app/app-deployment.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "king01286@naver.com"
          git config --local user.name "CJ-Park"
          
          git add manifest/app/app-deployment.yaml
          git commit -m "Update manifest deployment yaml file for argoCD"
          git push